#########################################################################################
# Config for a 'provider' participant profile
#########################################################################################

#########################################################################################
# EDC Connector config for provider
#########################################################################################
# the participant id to be used as assigner in policies as expected by the EDC connector on contract negotiation
edc-connector.participant.id=provider
# tier2 url to the provider EDC connector service behind the TLS gateway (ending with the route context name)
# this will be enriched in the SD json by enrichAndValidate API
edc-connector.tier2-base-url=https://tls.participant.provider.dev.simpl-europe.eu/edc

