
#########################################################################################
# Config for a 'consumer' participant profile
#########################################################################################

#########################################################################################
# EDC Connector config for consumer
#########################################################################################
edc-connector.api-key.value=apikeydefaultvalue

