
#########################################################################################
# Config for a 'consumer' participant profile
#########################################################################################

#########################################################################################
# EDC Connector config for consumer
#########################################################################################
edc-connector.api-key.value=apikeydefaultvalue


#########################################################################################
# Kafka
#########################################################################################

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=contract_consumption
spring.kafka.consumer.auto-offset-reset=earliest

# topic used for checking the transfer status
kafka.transfer-status.topic=contract_consumption.transfer_status
# maximum number of retry attempts for backoff
kafka.transfer-status.backoff.max-attempts=10
# initial backoff interval in milliseconds
kafka.transfer-status.backoff.interval=5000
# double value to multiply the backoff interval after each failure
kafka.transfer-status.backoff.multiplier=1.0

# topic used for transfer deprovisioning after transfer completion
kafka.transfer-deprovisioning.topic=contract_consumption.transfer_deprovisioning
# maximum number of retry attempts for backoff
kafka.transfer-deprovisioning.backoff.max-attempts=5
# initial backoff interval in milliseconds
kafka.transfer-deprovisioning.backoff.interval=5000
# double value to multiply the backoff interval after each failure
kafka.transfer-deprovisioning.backoff.multiplier=1.0

# if true, the application will fail to start if the Kafka broker is not available
kafka.fatal-if-broker-not-available=true

# can be one of: SASL_PLAINTEXT (if blank no auth enabled)
kafka.auth.type=SASL_PLAINTEXT
kafka.auth.sasl.username=
kafka.auth.sasl.password=

