
#########################################################################################
# Config for testing (both provider and consumer profiles enabled)
#########################################################################################

#########################################################################################
# EDC Connector config (common)
#########################################################################################

# url to the provider EDC connector (internal service)
edc-connector.base-url=https://edc-provider.dev.simpl-europe.eu


#########################################################################################
# EDC Connector config (provider)
#########################################################################################

# the participant id to be used as assigner in policies as expected by the EDC connector on contract negotiation
edc-connector.participant.id=provider
# tier2 url to the provider EDC connector service behind the TLS gateway (ending with the route context name)
# this will be enriched in the SD json by enrichAndValidate API
edc-connector.tier2-base-url=https://tls.participant.provider.dev.simpl-europe.eu/edc


#########################################################################################
# EDC Connector config (consumer)
#########################################################################################

edc-connector.api-key.value=apikeydefaultvalue

