#########################################################################################
# Swagger ui & api docs
#########################################################################################
springdoc.api-docs.path=/api-docs
springdoc.api-docs.version=OPENAPI_3_0
springdoc.swagger-ui.path=/swagger-ui

# OpenAPI groups configuration: each group maps to controllers and is displayed separately in Swagger UI
openapi-config.groups[0].name=v1
openapi-config.groups[0].display-name=API v1
openapi-config.groups[0].packages-to-scan=eu.europa.ec.simpl.edcconnectoradapter.controller.v1

# comma separated list of servers url to be used by swagger
openapi-config.servers=https://edc-connector-adapter.dev.simpl-europe.eu

# Set the title for Swagger UI
openapi-config.title=EDC Connector Adapter API
openapi-config.description=APIs enable seamless communication with the EDC Connector, supporting a modular architecture that separates the responsibilities of asset/policy registration, contract negotiation and data consumption. This set of APIs facilitates secure, standardized, and traceable data exchange between providers and consumers in federated data ecosystems.\n\
    \n\
    ## Business Context\n\
    \n\
    The EDC Connector Adapter acts as an intermediary between provider-side and consumer-side applications and the EDC Connector. It enables:\n\
    \n\
    1. Registration and enrichment of assets and policies on the provider side.\n\
    \n\
    2. Discovery of data offers from provider connector catalog.\n\
    \n\
    3. Negotiation of usage contracts based on defined policies.\n\
    \n\
    4. Initiation and monitoring of data transfers.\n\
    \n\
    \n\
    ### Key Actors\n\
    \n\
    - **Provider**: Publishes data assets, defines contract terms, and registers policies.\n\
    \n\
    - **Consumer**: Searches for offers, negotiates contracts, and consumes data.\n\
    \n\
    ### Typical Flow\n\
    \n\
    1. Retrieve Participant Identity\n\
    \n\
    2. Register and Enrich Assets and Policies\n\
    \n\
    3. Retrieve Asset Details\n\
    \n\
    4. Initiate Contract Negotiation\n\
    \n\
    5. Check Contract Status\n\
    \n\
    6. Initiate Data Transfer\n\
    \n\
    7. Monitor Transfer Status
