# OpenTelemetry configuration for EDC Provider
# uncomment this line to enable tracking
#otel.traces.exporter=otlp
otel.logs.exporter=none

otel.exporter.otlp.endpoint=http://collector.common01.sandbox-cat-dat.simpl-europe.eu
otel.exporter.otlp.protocol=http/protobuf

otel.instrumentation.servlet.enabled=true
otel.instrumentation.jersey.enabled=true
otel.instrumentation.http-url-connection.enabled=true
otel.instrumentation.jdbc.enabled=false

otel.experimental.log.level=debug

otel.resource.attributes=service.name=edc-provider,deployment.environment=local
