apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ if .Values.serviceAccount }}{{ .Values.serviceAccount.name | default .Release.Name }}{{ else }}{{ .Release.Name }}{{ end }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
