sonar.tests=src/test/java
sonar.coverage.exclusions=\
  **/*Test.java,\
  **/*Application.java,\
  **/config/**/*.*,\
  **/constant/**/*.*,\
  **/controller/**/*.*,\
  **/dto/**/*.*,\
  **/exception/**/*.*,\
  **/model/**/*.*,\
  **/property/**/*.*\
